version: "3"
services:
  mysql:
    image: mysql:5.6
    container_name: speedy-mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    command: --default-authentication-plugin=mysql_native_password
  im:
    build: ./project/im
    container_name: speedy-im
    ports:
      - "8360:8360"
    depends_on:
      - mysql